/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
 * Generated on: 07-Feb-2024 22:47:13
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 21
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2023b.app/extern/include/tmwtypes.h 
 */
const int BL = 21;
const real64_T B[21] = {
   -0.09052875617128, 0.009722747694745,  0.01838996686929,  0.03195431491574,
    0.04915884133571,  0.06837674373478,  0.08774872525134,   0.1053566360378,
     0.1194195945823,   0.1284901981234,   0.1316232562652,   0.1284901981234,
     0.1194195945823,   0.1053566360378,  0.08774872525134,  0.06837674373478,
    0.04915884133571,  0.03195431491574,  0.01838996686929, 0.009722747694745,
   -0.09052875617128
};
